pipeline {
    agent any

    stages {
        stage('Checkout from Git') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Chyheeb/timesheet-devops.git'
            }
        }

        stage('Build with Maven') {
            steps {
                    sh 'mvn -version'
            }
        }
    }
}

