pipeline {
    agent any

    stages {
        stage('Checkout from Git') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Chyheeb/chihebMedini.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('student-management') {
                   sh 'java -version'
                   sh 'mvn -version'
                   sh 'mvn clean test'
               }
            }
        }
    }
}

